[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LombScargle = "fc60dff9-86e7-5f2f-a8a0-edeadbb75bd9"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Photometry = "af68cb61-81ac-52ed-8703-edc140936be4"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
VirtualObservatory = "d7ce213e-d3b9-4ed1-b00e-1146b7ac83e0"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"
